import { decorateBootstrap } from "@/lib/crm-data";
import { requireOrganizationContext } from "@/lib/organization-context";
import { prisma } from "@/lib/prisma";
import { isSuperAdminEmail } from "@/lib/super-admin-constants";
import type { BootstrapData } from "@/lib/crm-types";

export async function loadBootstrapData(): Promise<BootstrapData> {
  const context = await requireOrganizationContext();
  const organizationId = context.organizationId;
  const userId = context.userId;
  const organizationWhere = { organizationId };
  const personalWhere = { organizationId, userId };

  const [
    members,
    accounts,
    contacts,
    leads,
    opportunities,
    cases,
    products,
    priceBooks,
    priceBookEntries,
    events,
    calendarSources,
    quickTexts,
    quickTextFolders,
    knowledgeArticles,
    listEmails,
    messagingSessions,
    invoices,
    videoCalls,
    files,
    attachments,
    tasks,
    emailActivities,
    callActivities,
    partners,
    stores,
    campaigns,
    campaignMembers,
    recordLabels,
    marketingActivations,
    subscriptionCheckouts,
    customReports,
    customDashboards,
    notifications,
    notificationPreferences,
    guidanceItems,
    guidanceStates,
    userPreferences,
    setupShortcutStates,
    helpArticleStates,
    appNavPreferences,
    listViewPreferences,
    globalSearchRecents,
    agentforceMessages
  ] = await Promise.all([
    prisma.organizationMembership.findMany({
      where: { organizationId, status: "ACTIVE", user: { status: "ACTIVE" } },
      include: { user: true },
      orderBy: { user: { name: "asc" } }
    }),
    prisma.account.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.contact.findMany({ where: organizationWhere, include: { account: true }, orderBy: { updatedAt: "desc" } }),
    prisma.lead.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.opportunity.findMany({ where: organizationWhere, include: { account: true, contact: true }, orderBy: { updatedAt: "desc" } }),
    prisma.caseRecord.findMany({ where: organizationWhere, include: { account: true, contact: true }, orderBy: { updatedAt: "desc" } }),
    prisma.product.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.priceBook.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.priceBookEntry.findMany({ where: organizationWhere, include: { product: true, priceBook: true } }),
    prisma.event.findMany({ where: organizationWhere, orderBy: { startAt: "asc" } }),
    prisma.calendarSource.findMany({ where: personalWhere, orderBy: { updatedAt: "desc" } }),
    prisma.quickText.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.quickTextFolder.findMany({ where: organizationWhere }),
    prisma.knowledgeArticle.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.listEmail.findMany({ where: organizationWhere, orderBy: { createdAt: "desc" } }),
    prisma.messagingSession.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.invoice.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.videoCall.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.fileRecord.findMany({ where: organizationWhere, orderBy: { uploadedAt: "desc" } }),
    prisma.attachmentRecord.findMany({ where: organizationWhere, orderBy: { uploadedAt: "desc" } }),
    prisma.task.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.emailActivity.findMany({ where: organizationWhere, orderBy: { sentAt: "desc" } }),
    prisma.callActivity.findMany({ where: organizationWhere, orderBy: { completedAt: "desc" } }),
    prisma.partner.findMany({ where: organizationWhere }),
    prisma.marketingStore.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.campaign.findMany({ where: organizationWhere, orderBy: { updatedAt: "desc" } }),
    prisma.campaignMember.findMany({ where: organizationWhere, orderBy: { createdAt: "desc" } }),
    prisma.recordLabel.findMany({ where: organizationWhere, orderBy: { createdAt: "desc" } }),
    prisma.marketingActivation.findMany({ where: organizationWhere, orderBy: { activatedAt: "desc" } }),
    prisma.subscriptionCheckout.findMany({ where: organizationWhere, orderBy: { createdAt: "desc" } }),
    prisma.customReport.findMany({ where: personalWhere, orderBy: { updatedAt: "desc" } }),
    prisma.customDashboard.findMany({ where: personalWhere, orderBy: { updatedAt: "desc" } }),
    prisma.notification.findMany({ where: personalWhere, orderBy: { createdAt: "desc" } }),
    prisma.notificationPreference.findMany({ where: personalWhere }),
    prisma.guidanceItem.findMany({ orderBy: { createdAt: "asc" } }),
    prisma.userGuidanceState.findMany({ where: personalWhere }),
    prisma.userPreference.findMany({ where: personalWhere }),
    prisma.setupShortcutState.findMany({ where: personalWhere, orderBy: { updatedAt: "desc" } }),
    prisma.helpArticleState.findMany({ where: personalWhere, orderBy: { updatedAt: "desc" } }),
    prisma.appNavPreference.findMany({ where: personalWhere }),
    prisma.listViewPreference.findMany({ where: personalWhere }),
    prisma.globalSearchRecent.findMany({ where: personalWhere, orderBy: { updatedAt: "desc" }, take: 8 }),
    prisma.agentforceMessage.findMany({ where: personalWhere, orderBy: { createdAt: "desc" }, take: 30 }).then((rows) => rows.reverse())
  ]);

  const payload: BootstrapData = {
    user: context.user,
    users: members.map((row) => row.user),
    organization: { id: context.organization.id, name: context.organization.name, slug: context.organization.slug, role: context.role },
    organizations: context.availableOrganizations,
    organizationRole: context.role,
    isSuperAdmin: isSuperAdminEmail(context.user.email),
    accounts,
    contacts,
    leads,
    opportunities,
    cases,
    products,
    priceBooks,
    priceBookEntries,
    events,
    calendarSources,
    quickTexts,
    quickTextFolders,
    knowledgeArticles,
    listEmails,
    messagingSessions,
    invoices,
    videoCalls,
    files,
    attachments,
    tasks,
    emailActivities,
    callActivities,
    partners,
    stores,
    campaigns,
    campaignMembers,
    recordLabels,
    marketingActivations,
    subscriptionCheckouts,
    customReports,
    customDashboards,
    notifications,
    notificationPreferences,
    guidanceItems,
    guidanceStates,
    userPreferences,
    setupShortcutStates,
    helpArticleStates,
    appNavPreferences,
    listViewPreferences,
    globalSearchRecents,
    agentforceMessages
  };

  return decorateBootstrap(JSON.parse(JSON.stringify(payload)) as BootstrapData);
}
